Upload page
RomanDovgii/moscow-polytech-portfolio pull request #1
Opened 2021-04-28 11:11 UTC by Ilya-Bykovskii

Добавил стилизацию для страницы загрузки проекта  в соответствующую папку (src>scss>upload). Стили адаптивны для десктопа, таблета и мобилок. 
Также внес некоторые правки в верстку: исправил опечатки; добавил обертку promo__wrapper для блока promo для того, чтобы на сам блок можно было повесить background-image и было удобнее структурировать promo.

Все файлы расположены в соответсвии с BEM-ом:
/Block
- /__elements
- /--modifs
- block.scsss

2021-04-28 18:44 UTC, RomanDovgii requested changes

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/style.scss
> +body {
Выносим такое в general.scss

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/main.scss
> +@import './upload-form/upload-form.scss'; // блок с формой для отправки проекта
folder-hell

Аккуратнее с этим, мы с тобой тот момент обсуждали.

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/fonts.scss
> +@font-face {
Лучше пока не подключай, ибо сделал неправильно. Просто фигач обычным шрифтом, PP пока не требуется.

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/promo/promo.scss
> +        @media (max-width: $sm) {
Давай это все в конец файла сгружать. Пока нет нормальной поддержки media-queries для отдельных блоков - все компонуем в конец.

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/upload-form/--upload-form/--cover.scss
> +.upload-form__label--cover::after {
Добро пожаловать в folder-hell, говорил выше, вспоминай, что говорил

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/upload-form/--upload-form/--cover.scss
> +    // background: red;
И кому ты это оставил?

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/promo/promo.scss
> +        .promo__lable, .promo__title {
Первого класса в верстке нет

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/upload-form/--upload-form/--cover.scss
> +.upload-form__input--cover {
Это что ты пытался сделать?

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/upload-form/--upload-form/--project.scss
> +    // background: red;
На кого ты его оставил?

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/upload-form/--upload-form/--video.scss
> +    // background: red;
Три штуки

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/upload-form/__upload-form/__form.scss
> +    @media (min-width: $sm) { /// tablet
А комментарий на кого?

2021-04-28 18:44 UTC, RomanDovgii commented on src/scss/upload/main/upload-form/__upload-form/__lable.scss
> +        margin-top: 2px;
Игнорь настолько малые отступы. И тут вложенность не нужна

2021-04-28 18:44 UTC, RomanDovgii commented on .gitignore
>  # Вспомогательные файлы
Убирай изменения отсюда, сейчас пофикшу

2021-04-29 09:18 UTC, Ilya-Bykovskii commented
Исправил фа1ловую структуру, обновил верстку с основного репозитория и заменил, где смог vw

2025-04-22 17:25 UTC, closed without merging